const GET_ERRORS = 'GET_ERRORS';
const SET_CURRENT_USER = 'SET_CURRENT_USER';
const SEND_NEW_URL = 'SEND_NEW_URL';
const GET_ALL_URLS = 'GET_ALL_URLS';
const SET_ALL_URLS = 'SET_ALL_URLS';
const LOGIN_USER = 'LOGIN_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const REGISTER_USER = 'REGISTER_USER';
const CLICK_SHORT_CODE = 'CLICK_SHORT_CODE';

export default {
  GET_ERRORS,
  SET_CURRENT_USER,
  SEND_NEW_URL,
  GET_ALL_URLS,
  SET_ALL_URLS,
  LOGIN_USER,
  LOGOUT_USER,
  REGISTER_USER,
  CLICK_SHORT_CODE
};